language: node_js
node_js:
  - "8"
stages:
  - lint
  - build
  - test
lint:
  stage: lint
  script:
    - npm run lint
build:
  stage: build
  before_script:
    - npm install -g babel-cli rollup
  script:
    - npm run build
test:
  stage: test
  script:
    - npm run test    
