language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: build and test
      before_script:
        - npm install -g babel-cli rollup
      script:
        - npm run build
        - npm run test