language: node_js
node_js:
- '8'
jobs:
  include:
  - stage: lint
    script:
    - npm run lint
  - stage: build and test
    before_script:
    - npm install -g babel-cli rollup
    script:
    - npm run build
    - npm run test
# deploy:
#   provider: npm
#   email: jefree.sujit@gmail.com
#   api_key:
#     secure: nNSJX0GS+bpzPwb5/6wAync1QCUqzim5C0bPOUsY0bvxlrncDNyY/8NMV0M68cNC8yNRFhXYCeEfr9l6TAlK7wint95sjBwKwTybBQhWoH9NrCoNOcIfDiRrnDSYErxK1/pS/JTZFzGKApHXqCeldHr2y+WWwFixTTfboPwTKjxrZLm1txemmM0gL+BapnSoUNElauqYziy1QuKvLJBCSJXbuCs2yGY9877sy7TB3/s5oIQge7r0iRuKgoBK6mth3WE3V8Wy5cDEZTpZf0kiCXqmvzmobFBQja+JqrBAa78xiDnOcMo6iMAczEgofW8UCbXN41YddwnjY38iXpen2Z9/xcqhfzYEzZlzcmoUHABqzArBiOAvunwI37wggNkos2CApYaa2joGxpPOh3yrTJF7EH5IPRgHQ/Gt1Ib6zLa+Os71K4N2uMOew/1aeWvct18i7kk1t4DMWALg1Of9HDlEIsUNxKyJOOmEYUIeDGVnXvFPX2tuw8pqx4zwu7CdZXMowEFrLd7KgxnSwbvzTZPsKvnscmKFcqnN33p5ssdHPzd7j77QA4z+w8LYGR8TSBwp0THv5Z311q99nNBG5oum6sgk2/QFybgFfTuz6mehO8mVRhe740ye0Z/8VfvxRszsovST12ZzFjdkIji5AikQxc35b0WZGP4/ZNqH4gQ=
#   on:
#     tags: true
#     repo: Jefreesujit/react-context-redux
#     branch: master
#   skip_cleanup: true

